### ISSUE TITLE
Error in example...

### ISSUE THREAD

**Issue by coforfe** [haghish/autoEnsemble#2]
Hi,
Thanks for your very interesting package.

I was reading your documentation and reproducing the code in the example and I got two errors in this:

```r
> h2o.auc(top$model)
Error in top$model : $ operator not defined for this S4 class
```
and here:

```r
> h2o.auc(search$model)
Error in search$model : $ operator not defined for this S4 class
```
Also, regarding the title of your package in CRAN `for Severe Class Imbalance`, do you have a reference to check where this approach of several ensembles has advantages with respect to other methods?.

Thanks!
Carlos.

**Comment by haghish** [comment]
This code is for the "developmental version" of the package. If you install it from CRAN, use the examples in the functions' helpfiles

**Comment by coforfe** [comment]
OK.
Thanks for the clarifications.
